import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Header from "../components/Header/Header";
import Banner from "../components/Banner/Banner";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  

  return (
    <>
      <Head>
        <title>GlobeTrot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      {/* Banner */}
      <Banner/>
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
        {/* Pull some data from server */}
        </section>
      </main>
    </>
  );
}
// export async function getStaticProps(){
  
// }